security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
google:
  client:
    # https://console.developers.google.com/apis/credentials?project=tut-spring-boot-oauth2&pli=1
    clientId: 678181184380-2o32hl7oj76qacfhvt0pbkpq2fctp4ct.apps.googleusercontent.com
    clientSecret: PAPXFtx7V5wbRmX63WI9273O
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    tokenName: access_token
    scope:
      # https://developers.google.com/+/web/api/rest/oauth#profile
      - profile
      - https://www.googleapis.com/auth/plus.login
      - email
      - openid
      - https://www.googleapis.com/auth/plus.me
    authenticationScheme: query
    clientAuthenticationScheme: form
    preEstablishedRedirectUri: http://localhost:8080/login/google
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
#    userInfoUri: https://www.googleapis.com/plus/v1/people/me/openIdConnect
    tokenInfoUri: https://www.googleapis.com/oauth2/v3/tokeninfo
    preferTokenInfo: true
microsoft:
  client:
    # https://apps.dev.microsoft.com/#/application/07e159c5-0726-4e64-998a-fb88d4fcf0c4
    clientId: 07e159c5-0726-4e64-998a-fb88d4fcf0c4
    clientSecret: fqaYQubbdoqEqkPk4kfi7Qm
    userAuthorizationUri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
    accessTokenUri: https://login.microsoftonline.com/common/oauth2/v2.0/token
    scope:
      # https://docs.microsoft.com/en-gb/azure/active-directory/develop/active-directory-v2-scopes
      - profile
      - email
      - openid
#      - https://graph.microsoft.com/mail.read
      - https://graph.microsoft.com/User.Read
    clientAuthenticationScheme: form
  resource:
    # https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_get#example
    userInfoUri: https://graph.microsoft.com/v1.0/me
twitter:
  client:
    # https://apps.twitter.com/app/7631631/show
    clientId: BWjEsrsixzTTcr6yfj87qY8cI
    clientSecret: ZsrpLbyySwb0nHerXWwduJgUzvBCRMh6IJuMDbN8dGm7GreSya
    userAuthorizationUri: https://api.twitter.com/oauth/authorize
#    userAuthorizationUri: https://api.twitter.com/oauth/authenticate
#    userAuthorizationUri: https://api.twitter.com/oauth/request_token
    accessTokenUri: https://api.twitter.com/oauth/access_token
#    tokenName: oauth_token
#    authenticationScheme: query
    authenticationScheme: form
    scope:
      # https://dev.twitter.com/oauth/overview/application-permission-model
      - read
    clientAuthenticationScheme: form
    preEstablishedRedirectUri: http://localhost:8080/login/twitter
  resource:
    # https://dev.twitter.com/rest/reference/get/users/lookup
#    userInfoUri: https://api.twitter.com/1.1/users/lookup.json
    userInfoUri:  https://api.twitter.com/1.1/users/show.json
linkedin:
  client:
    clientId: 81om4awiw4mdd0
    clientSecret: b688lpVpilUSLxzG
    accessTokenUri: https://www.linkedin.com/oauth/v2/accessToken
    userAuthorizationUri: https://www.linkedin.com/oauth/v2/authorization
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.linkedin.com/v1/people/~?format=json
uaa:
  # mvn -pl github -Dserver.contextPath=/myapp spring-boot:run
  # http://localhost:8080/myapp/login/uaa
  # http://localhost:8080/myapp/me
  client:
    clientId: mywebapp
    clientSecret: changeme
    accessTokenUri: http://localhost:9999/oauth/token
    userAuthorizationUri: http://localhost:9999/oauth/authorize
    authenticationScheme: header
  resource:
    userInfoUri: http://localhost:9999/userinfo
    tokenInfoUri: http://localhost:9999/check_token

logging:
  level:
    com.example: DEBUG
    org.springframework.security: DEBUG
    org.apache.http.wire: DEBUG
    org.springframework.web.client.RestTemplate: TRACE
    org.springframework.boot.autoconfigure.security.oauth2: DEBUG
