security:
  oauth2:
    client:
      clientId: 678181184380-2o32hl7oj76qacfhvt0pbkpq2fctp4ct.apps.googleusercontent.com
      clientSecret: PAPXFtx7V5wbRmX63WI9273O
      accessTokenUri: https://accounts.google.com/o/oauth2/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: authorization_code
      scope:
        - https://www.googleapis.com/auth/userinfo.email
        - https://www.googleapis.com/auth/userinfo.profile
      authenticationScheme: query
      clientAuthenticationScheme: form
      preEstablishedRedirectUri: http://localhost:8080/login
    resource:
      userInfoUri: https://www.googleapis.com/auth/plus.me
#      userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo
